POST http://localhost:3000/turnos
Content-Type: application/json

{
  "fecha_turno": "2025-12-01",
  "hora_turno": "10:30",
  "estado": "pendiente",
  "motivo_consulta": "Control general",
  "observaciones": "",
  "especialidad": { "id_especialidad": 1 },
  "id_profesional": 1,
  "id_sede": 1,
  "id_usuario": 1
}
